#### Arduino

BOARD_TAG   = nano
BOARD_SUB   = atmega328old
# BOARD_SUB   = atmega328
ARDUINO_PORT=/dev/ttyUSB0
ARDUINO_LIBS=LiquidCrystal Wire RTClib Adafruit_BusIO SPI EEPROM

include /usr/share/arduino/Arduino.mk
