#### Arduino

BOARD_TAG   = nano
# BOARD_SUB   = atmega330old
BOARD_SUB   = atmega328
ARDUINO_PORT=/dev/ttyUSB0
#ARDUINO_LIBS=Adafruit_Unified_Sensor DHT_sensor_library LiquidCrystal Wire RTClib Adafruit_BusIO Adafruit_AHTX0 SPI EEPROM

include /usr/share/arduino/Arduino.mk
